# Generated by Django 4.2.3 on 2023-11-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_card_last_updated_survey_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
